routes/web.php
<?php

use App\Http\Controllers\CandidateController;
use App\Http\Controllers\EmployerController;
use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('layout.master');
});

Route::get('jobPortal/register/', function () {
    return view('global_register');
});

Route::get('jobPortal/login/', function () {
    return view('global_login');
});

Route::get('jobportal/employer/register', function () {
    return view('employer_register');
});

Route::post('jobportal/employer/register', [EmployerController::class, 'store'])->name('employer.register');

Route::get('jobportal/employer/login', function () {
    return view('employer_login');
});

Route::post('jobportal/employer/login', [EmployerController::class, 'login'])->name('employer.login');

Route::get('jobportal/employer/dashboard', [EmployerController::class, 'dashboard'])->name('employer.dashboard');

Route::get('jobportal/job/post', [EmployerController::class, 'postJobView']);

Route::post('jobportal/job/post', [EmployerController::class, 'postJob'])->name('postJob');

Route::get('jobportal/employer/my_jobs', [EmployerController::class, 'showJobs'])->name('employer.showJob');

Route::get('jobportal/job/showApplications/{id}', [EmployerController::class, 'showApplication'])->name('showCandidates');

Route::get('jobportal/candidate/register', function () {
    return view('candidate_repo.candidate_register');
});
Route::post('jobportal/candidate/register', [CandidateController::class, 'candidateStore'])->name('candidate.register');

Route::get('jobportal/candidate/login', [CandidateController::class, 'candidateLogin'])->name('candidate.login');
Route::post('jobportal/candidate/login', [CandidateController::class, 'candidateLoginValidation'])->name('candidate.loginValidation');

Route::get('jobportal/candidate/dashboard', [CandidateController::class, 'candidateDashboard'])->name('candidateDashboard');

Route::get('jobportal/candidate/showJobs', [CandidateController::class, 'searchJobs'])->name('searchJobs');
Route::post('jobportal/candidate/show', [CandidateController::class, 'search'])->name('fetchJobs');

Route::get('jobPortal/candidate/display/job/{id}', [CandidateController::class, 'jobDetails'])->name('displayJobDetails');

Route::get('jobPortal/candidate/apply/job/{id}', [CandidateController::class, 'jobApply'])->name('applyJob');
Route::get('jobPortal/candidate/myAppliedJobs', [CandidateController::class, 'showApplications'])->name('myAppliedJobs');

app/Http/Controllers/EmployerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployerLoginRequest;
use App\Http\Requests\EmployerRequest;
use App\Http\Requests\JobPostRequest;
use App\Models\Employer;
use App\Models\Location;
use App\Models\Job;
use App\Models\JobType;
use Illuminate\Support\Facades\Session;

use Locale;

class EmployerController extends Controller
{


    public function store(EmployerRequest $request)
    {
        $employerData = $request->validated();
        Employer::create($employerData);
        return redirect('jobportal/employer/login');
    }

    public function login(EmployerLoginRequest $request)
    {
        $emp =  Employer::where(['email_address' => $request->email_address, 'password' => $request->password])->first();
        if (isset($emp)) {
            Session::put('employer_id', $emp->id);
            Session::put('employer_email_address', $request->email_address);
            Session::put('employer_first_name', $emp->first_name);
            return redirect('jobportal/employer/dashboard');
        } else {
            return "Data with provided Credentials Not Found";
        }
    }

    public function dashboard()
    {
        return view('employer_repo.employer_dashboard');
    }


    public function postJobView()
    {
        return view('employer_repo.post_job');
    }

    public function postJob(JobPostRequest $request)
    {
        $jobData = $request->validated();
        Job::create($jobData);
        return redirect('jobportal/employer/my_jobs');
    }

    public function showJobs()
    {
        $employer = Job::with('job_type', 'location')->withCount('candidate')->where('employer_id', Session::get('employer_id'))->get();
        return view('employer_repo.show_jobs', ['jobs' => $employer]);
    }

    public function showApplication($id)
    {

        return Job::with('candidate')->find($id);
    }
}

resources/views/employer_repo/employer_dashboard.blade.php
@extends("layout.employer_dashboard_layout")
@push('css')
<link rel="stylesheet" href="{{asset('/css/employer_dashboard.css')}}">
@endpush

@section('content')
<h1>Job Portal</h1>
<h1>Hi, {{Session::get('employer_first_name')}}</h1>
@endsection

resources/views/employer_repo/employer_show_applicants.blade.php
@extends('layout.candidate_dashboard_layout.blade.php')
@section('content')

<table>
    @foreach()
    @endforeach
</table>
@endsection

resources/views/employer_repo/post_job.blade.php
@extends("layout.employer_dashboard_layout")
@push('css')
<link rel="stylesheet" href="{{asset('/css/job_post.css/')}}">
@endpush
@section('content')
<form action="" method="post" class="employer_job_post_form">


    @csrf
    <table>
        <tr>
            <td> <label for="jobTitle">Job Title</label></td>
            <td> <input type="text" name="job_title" id="jobTitle"> </td>
            <td>
                @error('job_title')
                {{$message}}
                @enderror
            </td>
        </tr>
        <tr>
            <td> <label for="jobDescription">Description</label></td>
            <td>
                <textarea name="job_description" id="jobDescription" cols="30" rows="10"></textarea>
            </td>
            <td>
                @error('job_description')
                {{$message}}
                @enderror
            </td>
        </tr>
        <tr>
            <td>
                <label for="budget">Budget(CTC)</label>
            </td>
            <td>
                <input type="text" name="budget" id="budget">

            </td>
            <td>
                @error('budget')
                {{$message}}
                @enderror
            </td>
        </tr>
        <tr>
            <td> <label for="">Job Type</label></td>
            <td>
                <select name="job_type_id" id="">
                    <option value="">Job Type</option>
                    @foreach($job_types as $job_type)
                    <option value="{{$job_type['id']}}">{{$job_type['job_type']}}</option>
                    @endforeach

                </select>
            </td>
        </tr>
        <tr>
            <td> <label for="">Job Location</label></td>
            <td>
                <select name="location_id" id="">
                    <option value="">Location</option>
                    @foreach($location_composer as $location)
                    <option value="{{$location['id']}}">{{ $location['city'] }}</option>
                    @endforeach
                </select>
            </td>
            <td>
              
                <input type="hidden" name="employer_id" value="{{Session::get('employer_id')}}">
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="POST">
            </td>
        </tr>
        <tr>
        </tr>
    </table>

</form>
@endSection

resources/views/employer_repo/show_jobs.blade.php
@extends("layout.employer_dashboard_layout")
@push('css')
<link rel="stylesheet" href="{{asset('/css/show_jobs.css')}}">
@endpush
@section('content')

<h1>My Jobs</h1>
<table>
    <tr>
        <th>Job Title</th>
        <th>Job Location</th>
        <th>Max CTC Budget</th>
        <th>Job Type</th>
        <th>Applications</th>
        <th>Actions</th>
    </tr>

    @foreach($jobs as $job)
    <tr>

        <td>
            <a href=""> {{$job['job_title']}} </a>
        </td>
        <td>
            {{$job->location->city}}
        </td>
        <td>
            {{$job['budget']}}
        </td>
        <td>
            {{$job->job_type->job_type}}
        </td>
        <td>
            <a href="{{route('showCandidates',['id'=>$job->id])}}">
                {{$job->candidate_count}}
            </a>
        </td>
        <td>

            <a href="">Edit</a>
            <a href="">Delete</a>
        </td>
    </tr>
    @endforeach
</table>
@endsection